server:
  port: 8085
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/client
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka
