spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orders
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml
  application:
    name: order-service
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      bootstrap-servers: localhost:9092
topic:
    name:
      order: order
      delivery: delivery
kafka:
    partitions:
      count: 1
    replicas:
      count: 1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka
server:
  port: 8082

