spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/restaurant
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml
  application:
    name: restaurant-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka
server:
  port: 8083