spring:
  cloud:
    gateway:
      routes:
        - id: delivery-man-service
          uri: lb://delivery-man-service
          predicates:
            - Path=/api/v1/delivery-man/**

        - id: delivery-service
          uri: lb://delivery-service
          predicates:
            - Path=/api/v1/delivery/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/order/**

        - id: restaurant-service
          uri: lb://restaurant-service
          predicates:
            - Path=/api/v1/restaurant/**
